# .streamlit/secrets.toml
stripe_secret_key = "sk_test_51T2G7rCXjBvgJROcYcQvbLNkr8AIe8stlN4dqvg2Y7OOHuhnPjQnbin5GgwMiuYVvqY3HTPreio5FQXyS9gCbWBi00NLPMKf32"
stripe_publishable_key = "pk_test_51T2G7rCXjBvgJROc3i2DN38xjPYf6Bts9aw4fpkyOAbHbpPYGCd076fbORGkQHTZuM0A6N9I1heFb0H8RXph8QZg009l0xzZoo"

stripe_price_pro = "price_1234567890abcdef"  # später einfügen
stripe_price_enterprise = "price_1234567890ghijkl"  # später einfügen

app_url = "http://localhost:8501"  # später: deine Streamlit Cloud URL
