# LIVE KEYS f√ºr Production
stripe_secret_key = "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"
stripe_publishable_key = "pk_live_51T2G7rCXjBvgJROcQPqby9xv8DYHws88cPgzc5yGtKm6QzjgF1fAliPGvlIMTh6lW3xK7UXnvEiZKLz1gYV0rc4L00RoHcVkil"

# Price IDs von den Produkten
stripe_price_pro = "price_1234567890abcdef..."
stripe_price_enterprise = "price_1234567890ghijkl..."

# Deine Streamlit App URL
app_url = "https://spinegraphics.streamlit.app"


pk_live_51T2G7rCXjBvgJROcQPqby9xv8DYHws88cPgzc5yGtKm6QzjgF1fAliPGvlIMTh6lW3xK7UXnvEiZKLz1gYV0rc4L00RoHcVkil
