# .streamlit/secrets.toml
stripe_secret_key = "sk_test_51T2G7rCXjBvgJROc..."
stripe_publishable_key = "pk_test_51T2G7rCXjBvgJROc..."

stripe_price_pro = "price_1234567890abcdef"  # später einfügen
stripe_price_enterprise = "price_1234567890ghijkl"  # später einfügen

app_url = "http://localhost:8501"  # später: deine Streamlit Cloud URL
